lastVideo = 1; 

var videoList = ['filler', 
'<video width="100%" autoplay controls><source src="tutorials/OBS_Livesaver/BasicUser/FirstLogin.mp4" type="video/mp4">Your browser does not support the video tag.</video>', 

'<video width="100%" autoplay controls><source src="tutorials/OBS_Livesaver/BasicUser/OpeningTemplates.mp4" type="video/mp4">Your browser does not support the video tag.</video>', 

'<video width="100%" autoplay controls><source src="tutorials/OBS_Livesaver/BasicUser/FindSubmissionAndGetDocumentList.mp4" type="video/mp4">Your browser does not support the video tag.</video>', 

'<video width="100%" autoplay controls><source src="tutorials/OBS_Livesaver/BasicUser/OverwriteAndForceDSTS.mp4" type="video/mp4">Your browser does not support the video tag.</video>', 

'<video width="100%" autoplay controls><source src="tutorials/OBS_Livesaver/BasicUser/SavingDataVersion2.mp4" type="video/mp4">Your browser does not support the video tag.</video>',

'<video width="100%" autoplay controls><source src="tutorials/OBS_Livesaver/BasicUser/VersionControl.mp4" type="video/mp4">Your browser does not support the video tag.</video>',

'<video width="100%" autoplay controls><source src="tutorials/OBS_Livesaver/TemplateUser/ManageTemplateWindow.mp4" type="video/mp4">Your browser does not support the video tag.</video>',

'<video width="100%" autoplay controls><source src="tutorials/OBS_Livesaver/TemplateUser/CreatingTemplates.mp4" type="video/mp4">Your browser does not support the video tag.</video>',

'<video width="100%" autoplay controls><source src="tutorials/OBS_Livesaver/TemplateUser/EditAndDeleteTemplates.mp4" type="video/mp4">Your browser does not support the video tag.</video>',

'<video width="100%" autoplay controls><source src="tutorials/OBS_Livesaver/TemplateUser/InsertFields.mp4" type="video/mp4">Your browser does not support the video tag.</video>',

'<video width="100%" autoplay controls><source src="tutorials/OBS_Livesaver/TemplateUser/ManageFields1.mp4" type="video/mp4">Your browser does not support the video tag.</video>',

'<video width="100%" autoplay controls><source src="tutorials/OBS_Livesaver/TemplateUser/ManageFields2.mp4" type="video/mp4">Your browser does not support the video tag.</video>',

'<video width="100%" autoplay controls><source src="tutorials/OBS_Livesaver/TemplateUser/ManageFields3.mp4" type="video/mp4">Your browser does not support the video tag.</video>',
];

var titleList = ['filler',
'First Login', 
'Opening Templates',
'Find Submissions and Getting Documents',
'Load Data with Overwrite and Force DSTS',
'Saving Data',
'Saving Data with Version Control',

'Manage Template Overview',
'Creating Templates',
'Edit and Delete Templates',
'Insert Fields', 
'Manage Fields: Part 1', 
'Manage Fields: Part 2', 
'Manage Fields: Part 3',

'Manage Post NOC Changes',
'Navigate Post NOC Changes',
'Assess',

'Manage Reviews: Part 1',
'Manage Reviews: Part 2',
'Manage Reviews: Part 3',
'Manage Reviews: Part 4',
'Documents',
'Add Header',
'Scan Document',

];

var descriptionList = ['filler',
"Hi all, welcome to the BGTD screening and review tool tutorial series. I, Andrew Xing will be your guide for this module. Without further ado, let's log as first time user. We start by opening Microsoft Word, I have the 2013 version, it may look different from yours, but no worries, it will work the same way. Select the SRT tab at the top. Now, to connect to the application's databases, we will have to import a connection string file. And this connection file should have been provided to you already. Let's dropdown and the select import. Locate the connection file in your email and save it to a convenient location such as your myKey folder on your K drive. I've put mine on my desktop. This popup says we've been successfully connected, great, let's close it and log in. Press the login button and enter the username and password that you have been given. Since you are a first time user, you will be asked to change your password. Please keep in mind that the new password needs at least one special character, uppercase character, lowercase character and number. Additionally, you will be required to change your password every six months. Now that we're done entering the new information, let's save the password, and you're in! For all subsequent logins, your credentials will be saved to the computer and you will not need to enter your password. Let's show you how it's done. I'm just going to reopen Microsoft Word and press the connection button; and voila, you're in again.",
"Hi all, welcome back to the BGTD Screening and Review tool tutorial series. Today I'll be covering opening templates and populating data, a core function of the SRT. Let's begin with selecting the 'Open Template' button. A popup window appears and we see a list of all the available templates. We can sort and filter these templates by dropping down filter options and choosing a category or typing in a search term. We can also clear the filters by pressing the 'X' button. To open a template, simply select a template and press the open button or just double click. The template will open in a new document. We will notice that in this document, we have some text that will be highlighted when your mouse hovers over it. When you click this text, a box will surround it and a tag indicating the title of this text segment. These are called content control fields and they have the ability to extract information out of the SRT and DSTS database. To easily locate all of these content control fields in the document, we press the 'Eyeball icon' and they become highlighted. I'll explain the colour codes in more depth later, notice the blue highlighted field, this indicates the control number field. Click it, type in a drug's control number [134774: for Nyquil], and press the load button. Now we see that our content control fields will get populated with data corresponding to the control number. What if we want to load a different control number? Change the control number, click outside the content control field, select yes to clear all fields and simply press the load button again.",
"Hi all, welcome back to the BGTD Screening and review tool tutorial. This time, we will be covering finding submissions and getting document lists. Let's start by clicking the blue circle document icon, which opens the submission finder window. In here, we can find the control number(s) associated to a drug, manufacturer. Let's begin by searching for Nyquil, a popular cough syrup that is famous for tasting bad, but working. Notice each submission has its corresponding control number. Notice that we can sort the submissions numerically by control number and alphabetically by the product name and manufacturer. We can double click the submission to insert the control number into the content control field. To access the documents associated to a control number, we simply need a control number in the document (which we already have for Nyquil), now press the icon with multiple colourful documents. In this window, we can see the associated documents to the control number, select several, and by pressing generate table, the tool inserts a table of the selected documents right where your cursor lies.",
"Hi all, welcome back to the BGTD Screening and Review tool tutorial series. This time, we will be discussing the use of Overwrite and Force DSTS when it comes to loading data. In this example, we have data in our content control fields already, I've used dollar signs to make it easier to see. We enter in a control number and press load, however nothing changes because by nature, load will only fill the empty content control fields. Instead, we can overwrite the bogus data with real data by selecting overwrite and loading again. Notice that the popup says the data has been loaded from the SRT database, I will elaborate further on about this soon. Press ok, and voila, the dummy data has been replaced with information from the SRT database. For Force DSTS, we need to give a little bit of background information first. When we load the data, we look into two databases, first we check if there are any values tied to the control number in the SRT, if there are, then we load it into the content control field and that's it, if there aren't any, only then we look into the DSTS database to find relevant data. Using force DSTS will take the DSTS version of the data over the SRT version. Let's try it out. Clicking the load dropdown once again, we will see that overwrite is still checked; we will leave that checked so our load will overwrite data. Then, we select Force DSTS and load, and in our popup it says the data has been loaded from the DSTS database. Press ok, and we see no difference! Don't worry, this is because coincidentally, the DSTS loaded data is the same as the SRT data for this control number!",
"Hi all, welcome to the BGTD screening and review tool tutorial series. This lesson will quickly cover saving data to a control number. Within a lifespan of a drug, changes within the drug's specifications are likely to occur. If there is a change, we should save the changed data, so other users can access the new data.Just for proof of concept, let's look at control number 134774, which is for Vick's NyQuil Cough Medicine. If we press the reveal fields eyeball icon, it will highlight the fields. The blue field is the control number, green highlighted fields mean that your account privileges allow you to save data to this field, and yellow fields prohibit you from saving data to the field. So, let's just change all the contents of every field to 'testing' and hit the save button. In theory, the data in the green fields should have been saved to the SRT database. To prove this, let's use the clear all button, retype the control number, and press load. We can see that only the green content control fields have actually changed. Again, this data has only been saved to the SRT database, if we want to see the results of the DSTS database, we can just tick the force DSTS option, overwrite as well, and press load.",
"Hi all, welcome to the BGTD Screening and Review tool tutorial series. Today we will be covering version control for the save function. I'm going to begin with a scenario. So I'm using the save tool to save some data to a product name field for the control number 654321. I've changed the product name to 'Super Cough Syrup'. However, my co-worker is also tinkering with the control number 654321 and they decided to change the product name to 'Vick's Super Cough Syrup'. I'm going to log into the co-worker's account and do that real quick. So which product name is actually saved to the database? This is a trick question! They're both saved to the SRT, but the version we receive when we load the product name from 654321 is my co-workers version because it is the latest version. So let's quickly clear all fields, type in the control number, and load it, and we see 'Vick's Super Cough Syrup'. What if I want to see my version? Well, let's just log back into my account. And we'll just right click the product name control field, and under the versions tab, we select the one under my name. Alternatively, we can load my version by selecting the 'my version' option under load. So let's clear all fields first, type in the control number 654321, select 'my version', and then press load.",
"Hi all, welcome back to the BGTD screening and review tool tutorial series. This video will cover the use of multiple control numbers. Sometimes when a company changes something, it'll affect many drugs, let's say Proctor and Gamble change the formula for all their drugs end with 'quil', so like Nyquil and zzzquil, and as a result of that, the recommended dosage for all these drugs will have changed as well. So instead of filling out 5 new forms for each drug that ends with 'quil' we can just use the multiple control numbers functionality. Let's see how it works. First we need to open the 'assign multiple content control fields window', which is the box and arrows button up here. We add all the control numbers that are being affected by this change comma separated and then we add the content control fields that will have different data. So, for example, manufacturer name will not be moved because every control number here is a product of Proctor and Gamble, whereas the product name field will be added to the box on the right because all the products have a different name.When we're done with that, we'll close the window and open the 'apply multiple content control fields' window. Press the apply button, and a table will be created where your mouse lies. Let's fill out this table real quick…Ok we're done. We notice that the fields not included in the table are shared between all control numbers, like I mentioned above, an example is the manufacturer field, which is proctor and gamble. Saving and loading will also work with multiple control numbers. And that's all for this video, we'll see you in the next one.",
"Hi all, welcome to the BGTD screening and review tool tutorial series. Today, we will be discussing the use of default values when it comes to populating content control fields. Sometimes you would want to have your own unique value saved to a field. For example, fields like Quality reviewer name and reviewer division. And wouldn't it be nice if whenever you open a template, the Quality review name field and the reviewer division field would be automatically filled with your name and division? Turns out the SRT has a function just for this.So let's begin by just opening a Quality review template. Notice that the reviewer name field is blank, we'll make sure it gets filled out soon. To do that, let's close our template document, and under load, click the content controls default values button. And in this window, let's select the Quality Reviewer content control field, press the 'add' button, insert your name into the default values textbox, I'll put 'Andrew Xing', and I'll press save. Let's open the Quality review template again. And perfect, we see that the Reviewer Name field gets automatically populated with my name. That's all for default values, thanks for listening.",

"Hi and welcome to the tutorial on manage templates, this tutorial will be on what the manage template window contains. So let's get into it. You click this button to open the manage templates window. Here it is. Let's resize it to make it bit larger, so on the left hand side here you have a list of all the templates that you currently have available. If this list gets rather long and you can't find what you're looking for as quickly, you can drop down this filter options menu and filter by categories and search terms and you can always just clear your search by pressing this x button. On the right hand side, you will see a description of what each template is. So for example let's say GV's testing document, it's a file, the name of the file is GV's testing document, the document number is 0 and the following is the description and category. Now down at the bottom here we have the edit button which will allow us to edit the specifics of the template, you can also create a new template by pressing the new button and delete the selected button by pressing delete and the save button which will save your changes.",
"Hi there, welcome to the tutorial on making your own template, here I have a document with some text and a few fields, now let's say that I want to save this as a new template. First I need to open manage templates and then press the new button. Now since I am trying to upload a file, I'll just leave this checked off, if I wanted to upload a link, I'll just press this, but since this is a file, I'll just leave it as is. And just fill in the required information, for name let's just call this SRT test; document number let's say two; description, this is a test. Now for category, let's say we're not satisfied with any of these categories, so let's press this pencil button here. And it'll take me to the manage template categories, now here I can either add edit or delete categories, in my case I would like to add a testing category, so I'll press add button and in this textbox here, I'll just type in testing, I can cancel if I change my mind, but I think that's aright so I'll press save. Now let's close this window and select our new category in our dropdown menu, now that we've got through this, we can now upload our file. So you have two options, you can either upload your current document, or you can upload a different document in your computer, since I would like to upload this document here, I'll press upload current template, it's going to ask me to save it somewhere, I'm going to save this on my desktop. Down here you can see that our current document has been loaded and is ready to be saved so that means we're good to go. If you were to press upload template from a file instead, what this would do would is just ask you to upload from a specific area. But that's not what I need to do, so now that we're all done, we just press save and a pop up comes up that says our document template was successfully saved. Just press ok. And just to check if our template was saved correctly, we're going to open template and now since we've created that new category we can go to categories and filter by the new category we've just created and here it is, we open this and there's our template. Thanks for listening.",
"Hi, welcome to the SRT tutorial series, in this tutorial I would like to show you how to edit and delete templates, now as you can see I have manage templates open and I have selected the SRT test template Let's say I'd like to make some changes, maybe let's change the title to SRT test (edited), change the document number to 21 or just one and save. We get a popup saying that the template has been successfully updated which is great. And now all of our changes have been saved as we can see the details have changed and the title has changed as well. But what if I wanted to delete a template? Then it's quite simple, all I really have to is select the template again, press delete, there's a popup asking if I'm certain, since I am, I'll press yes, and that's all it takes, it's gone. So that's all there is for editing and deleting templates, I'll see you in the next video.",
"Hi there, welcome to the SRT tutorial series, in this video I'd like to show you how to insert fields into your document. In order to start, just press the insert field button up to here. Here you have a list of all the content control fields you can add to your document. In order to refine this list, you can press the filter options dropdown and filter by terms, for example clinical. You can clear the search bar by pressing the x button then you can filter by category. Let's say or you can filter by DSTS connection. In order to insert a field into your document you can single click and press the add button, or you can double click. Now, there are four different types of fields, each represented by their own different icon. If we take a field that I have already inserted into the document, this is a combo box control field, this one has multiple options for the user to choose form. The second type of field that I have inserted into the document is the date content control field. This one allows the user to pick a date using a calendar. The combo box control field is denoted with a down arrow circle. The date content control field is denoted with a calendar icon. Other types of fields that I didn't insert into the document is a text content control field and a rich text content control field, denoted by a '2a' icon and a purple 'a' icon respectively. The text content control field will only store plain text, so if you were to have lets say 'text', if you were to load this, it would just come out as text, not bolded. However, the rich text control field can store bolded text, italicized text and practically anything short of word art. And that's all there is to it. To both fields and the insert fields sidebar. I'll see you in the next video.",
"Hi there and welcome to the SRT video tutorial series, in this video, I'll be talking about the manage fields window. More like a brief introduction. Anyway, the reason you want to use the manage fields window is if you would like to add edit, or delete fields. TO open the window just press this little green gear up here. And the manage fields window will pop up. In the left hand side you have a list of the fields that are available to you and above that you can click the filter options drop down in order to filter the results by either the category or search term. And don here, you can further filter it by showing DSTS connected fields and by showing disabled fields. Now what disabled fields are, are basically deleted fields. No user can add a disabled fields but disabled fields can exist in t0ther documents, this disabled property is tied to this is active checkbox. Just a little bit a of a tease is in the future. Now once you selected a field you can see its details on its right hand side, you can see things such as the title, who can save to it, whether or not it's currently active as I've mentioned before, what in the DSTS database the field is tied to and so on. Now as I mentioned in the beginning, you can edit fields using this window, you can create a new one and you can deleted existing fields. That's where I'm going to stop for this video, in the next video, I'll start to create a new field, we'll talk about this top half here, exactly what all the properties mean, and how they affect the properties in the field. And in the video after the next one, we'll be going over the content control properties and the DSTS connection.",
"Hi there, welcome back to the SRT video tutorial series and in this video, we'll just be continuing from where we left off in the last one and we'll be creating a new control field. So in order to start I already have the mange fields window open, just in case you've forgot just press this little green button up here and once you get it open, press the new button down below. So when we're creating fields we'll just have to fill this up basically like a form. A tag isn't really something a user sees, all that we really care about is that it is a unique set of characters, let's call it SRTTEST2. Now the title is what the user sees so make sure to have something descriptive, so let's call it 'TEmplateTutorial'. Now the placeholder is automatically put into the field if the user doesn't change any of the contents, so let's say this is Option 1. I'm going to copy that for now for something later. Category is just whatever category that the tag fits in, so let's say dates for example. Down here we can select the type of the field. You can select rich text, plain text, date and content control content box. Content control combo box has some special steps to it so I'll select that. Now this doesn't apply for anything else, only for content control combo box. In order specify the other options, you need to put a semicolon and have a semicolon separated list for all the options that are available. Now, linked field is basically if the field doesn't have an item in an item or the DSTS database, then it will turn to the linked field and see if the field has anything in the SRT or DSTS database. For now I'm going to leave this blank. Now save privileges, who can save to this, let's just select admin, chief screening reviewer, system admin and let's select this. Now the other options. So the first on is whether or not it can have multiple instances. Basically if you can more than one of this field within your document, so I'll just select yes for now. Can assign default value is whether or not a user can set a default value personalized to them, I don't really see the need for that for my combo box, it's not going to be anything special or anything useful, so I'll leave that blank. Isactive is whether or not other users can insert it into their documents, for our purposes, yes we would like to insert our new fields into our documents to test whether or not it is working, so I'll leave that as is. And that's where I'm going to leave it for this video. In the next video I'm going to talk about the content control properties and tying the field to the DSTS, see you in the next one.",
"Hiya and welcome to the SRT tutorial series, in this video I'm continuing off the previous one, where we had created a template tutorial control field and we had set all the parameters in the top half here. So now we're talking about the content control properties and the DSTS connection. The content control properties are just properties of the control field itself. For example, prevent delete prevents the user from backspacing, deleting all the content inside the field, and deleting the field itself, so I shall keep that on for the purpose of the video. Lock editing just prevents the user from editing the field itself, I'll keep that off. And moving on to the DSTS connection. The DSTS connection part is how we connect to the DSTS database as the name suggests. Here we have a list of all the tables in the DSTS database, so if I want to connect to a particular value, I'll select the table I'm interested in and look for the specific field name, and I'm interested in the brand name here. So if I click this, it sends me a popup saying that the value of the DSTS database is already tied to a control field, and if I want to actually have two content control fields both tied to the same data. In this case, it's just a tutorial so I'll say yes. Now that that's done, we've filled all the information required for the field creation process, so let's save. That's great, we get a message that says that our update has went successfully. So let's check if this is working right, I already have a control field here that has the control number for Nyquil in it. So let's insert our control field, which is _TemplateTurtorial. Now, I mentioned before in the previous video that we have allow multiple instances on, as a result of that we can have two instances of _TemplateTutorial. Now this is how the combo box works, as you can see option 1 is automatically in there because of how placeholder behaves, and here is the list of all the other items exactly the way I typed it in. In the placeholder list, let's say I want option 3 for example, now just to prove that they're both the same, they both sync up. Now in order to show that this is actually connected to the DSTS database, let me just check off overwrite which I have, and then press load, and then press yes to the popup and now we get that it's Vick's Nyquil Cough Medicine which is what we expect because this is the brand name that is associated with this control number. And that's all there is to create a new field, now let's say you want to delete this field because you realize this isn't really going to help anybody, so let's delete it. So I've selected the field, all I need to do, press delete, then press yes, and we're good to go. That's all there is to the manage fields video, I'll see you in the next one.",

"Hi all, welcome to the BGTD screening and review tool tutorial series. In this video, we'll be discussing the 'manage screening documents' window, so let's open that up real quick. Everything from this window is pulled from the official POST NOC changes quality document. If there are any changes in that document, we'll have to update it on the SRT as well, so we'll do it from the 'manage screening documents window'. In this window we're going to see this listbox on left which just displays the title descriptions of model primary changes. Click on one of these changes and on the bottom, we will see the subchanges and subrequirements of said change. To the right, we'll see the list of conditions and supporting data required to fulfill this change. Today a new primary change was introduced. It's for POST-NOC drugs and it's called “change in the awesomeness of the drug'. Since we need to update the SRT to match the official documents, let's go under filter options, change the document reference to 'drugs' and press the new button and change the title to 'Change in the awesomeness of the drug'. Let's change the category to stability because everyone knows that the more awesome a drug is the more stable it is. It's got two subchanges, so we'll right click the listbox and press 'add subchange'. I'll just name them subchange 1 and subchange 2 for now. We can change the submission type through this dropdown, but I'll keep them at SNDS for now. If we right click conditions or supporting data, we can find the options add new condition and add existing condition. Let's add a new condition, right click it, toggle edit mode, and say 'Awesomeness level greater than or equal to 9'. We can also search for existing conditions, which saves us the hassle of typing in the new condition. So let's right click, add existing condition, search for 'quality', and either click the condition and press add, or just double click it to add it to the list. I'll just double click. It's the exact same thing for supporting data. Now that we've got our conditions and supporting data down, we need to add several of them to the subchanges. To do that, we just select Subchange 1 by clicking on it, check the desired conditions and supporting data, we'll just check them both, the conditions numbers will update corresponding to the ones you've checked. In subchange 2, we will only care about quality, so let's check that, and it only shows the number 2, corresponding to the quality condition.Now that we're all done, let's hit save, close the popup, and the primary change appears in the list. Of course, we can edit it again by selecting it and pressing edit. We can also move it up and down, approve the change, and publish the change to make it official. That's all folks. See you in the next one.",
"Hi all, welcome to the BGTD screening and review tool tutorial series. Today we'll be talking about the 'navigate changes' feature, without further ado, let's open this window by clicking the purple compass. Similar to the other windows in the screening section, we see a list of primary changes in the left listbox. We can filter this list by dropping down filter options and specifying different selection modes, drug stages, etc. Right now in the listbox below, we have all published primary changes from the post-NOC biologics reference document. Let's select a primary change by clicking on it. We see that the listboxes on the right populate with the change's conditions and supporting data. Click the dropdown button on a specific change to see its subchanges. Click arrow on a subchange to view its subrequirements. And if we click one of these subrequirements, we can see exactly what conditions or supporting data it needs for it to be fulfilled. You can always expand and collapse the entire list with the 'expand all' and 'collapse' button or increase the text size by dragging this scroll. That's all for now, thanks and I'll see you in the next one.",
"Hi all, welcome to the BGTD screening and review tool tutorial series. In this video we'll be discussing the use of the 'Assess' function in the screening section. So let's open the window up. If a manufacturer changes the specifications of the drug, they need to send in documents, and we need to examine the documents and generate a screening report. The assess tool basically makes that whole process a lot easier, I'll show you how. So Nyquil sends me this document, title says 'Manufacturing Facility Change', so I'll search that up in my window, and here it is. They say they have converted the facility from single product to multi-product. So it's this subchange right here, we'll just click it to select it. And by clicking it, we can see the associated conditions and supporting data only directed towards this subchange. Let's scan through the evidence Nyquil has provided us. Looks like the proposed change does not involve additional containment requirements, so we'll check 'Yes' for this condition. Uh oh, looks like Nyquil did not provide sufficient information describing the change-over procedures, so we'll check 'No' for the first supporting data. We'll also right click and create a comment stating there is insufficient information (“Insufficient information. Please elaborate on your procedures.”). And finally, it looks like they forgot to add cleaning procedures. So we'll put 'Not applicable' for the last supporting document. When you're all done, make sure to 'save', and then we'll generate our screening document. And voila, an automatically generated screening evaluation pops up where ever your cursor lies. If you've made a mistake, or want to edit the screening evaluation, we can go back to the assess tool and change something from there, save, and generate again, overwrite the contents, and we're all good. That's all for now, until the next one.",

"Hi all, welcome to the BGTD screening and review tool, today we'll talk about the manage reviews window, specifically the modules tab. So without further ado, let's get into it. In the left listbox, we'll see a list of all the modules under CTD biologics, we can change the structure document by selecting a different option in the listbox, but we'll stick with Biologics for now. To create a module, we'll just hit 'new', give it a title (Child 1), and press save. To add more layers to this section, we'll just right click the module and press add. Notice that the parent node is the section that you've right clicked. Add a title and save. And let's make another one just for the sake of it, add a title and save. Bear with me, we'll just make one last module under child one. Same thing, give it a title, save. Now you're probably wondering how to attach documents to modules. We can do this by right clicking an existing module, pressing edit, and then pressing the assign button. Now a new window opens, and it contains a huge list of documents. These are all documents added through this 'add document' button, or the documents tab. We can filter these documents to make life a bit easier and the select the desired one(s), hit accept. The documents appears in the listbox, and all we need to do is press save to save our changes. That's all for this tutorial, in the next one, I'll explain how you can add documents through the manage reviews window.",
"Hi all, welcome to the BGTD screening and review tool, today we'll talk about the manage reviews window, specifically the documents tab. So without further ado, let's get into it. We'll see a list of all the documents in the left listbox, if we drop down the filter options, we can see that they've been grouped by source. To create a new document, we'll just press the new button, enter in a title which will show up in the left listbox. Add information as required. So for description I'll just say that 'this is an example document'. For categories, I'll add one with the […] button, select anyone and hit accept. If you want to create a new category, just press the pencil icon, add a title and hit save. I'll discard for now. We can either attach text, a file, or a link to this document. I'll attach a file by pressing the upload file button, choosing a file, and pressing save. Now that we've created a new document, we can view it through the modules tab. If we right click any module, press edit, and then press assign. We can see that our document is here! That's all for this video, I'll see you in the next one.",
"Hi all, welcome to the BGTD screening and review tool, today we'll talk about two tabs in the manage reviews window. They're the Modules to Documents tab and the Documents to Modules tab. They are pretty straight forward so this tutorial will be a quick one. In modules to documents, we can find the documents associated to any available module. Just select a module by clicking on it and we'll see its associated documents. We can group these modules, which will alter the way they're sorted in the listbox below and we can also filter them by telling it to include direct modules, categories, subjects and tags. The documents to modules tab is the same thing but reversed. By selecting a module in the left listbox, we will see its associated modules in the right listbox, of course we can filter out the documents as well by direct modules, categories, subjects, and tags. That's all for this video folks, see you in the next one.",	
"Hi all, welcome to the BGTD screening and review tool tutorial series. Today, we will be discussing the manage reviews window, and the persons to documents and documents to persons tabs. We'll start with the persons to documents tab. In this tab, we can see that the right listbox includes a list of resource people. If you select a person, you can see the documents associated with them in the right listbox. In the documents to persons tab, we can assign resource people to specific documents. It's quite easy to do so. We'll just find a document using the search bar, and in the textbox to the right, we'll assign it to somebody, just type their name in there and then press save all changes. Now, if we open the window again and go back to the persons to documents tab, we'll see that under the name of the person you assigned it to will be the document that has been assigned. That's all for manage reviews. I'll see you in the next one.",
"Hi and welcome back to the SRT video tutorial series, in this video we will go over the documents tool. To access the documents sidebar, press the documents icon in the ribbon. Starting from the top, we have a filter options drop down. Here you can filter by Source, type, Status, category, tag, subject and search terms.  Source, Type and Status work the same way. Click the drop down and select what you are looking for. Category, Tag, and Subject work a bit differently. Press the … button and select what you are looking for. You can filter your options in this window, just type some terms in the text box and hit enter. Finally there is the good ol' search bar. Type out some terms in the search bar, as per usual you can also change it to an and query by pressing the or button. The X button will always clear the filter. Underneath Filter Options, we have the group by options. By default the documents are grouped by the source document. However, you can also group the by type, status, category, subject and tag. In order to expand each “category” just click on it, or you could press the expand all at the very bottom of the panel. You also have the option to collapse all if you need it. To view a document, just double click it. The only exception to this is when the document is just text. In this case it will be at the bottom of the side pane. Another item at the bottom of the side pane is the resource person. This is who you can contact if you have any questions regarding the document.",
"Hi and welcome back to the SRT video tutorial series. In this video we will be going into the add header tool. Once you are connected, click this blue icon here to open the Add Header sidebar.  Starting from the top, we have a drop down that allows you to pick the structure document. Underneath that there is a filter options dropdown. Once you click it, you'll see that you can filter by category, tag, subject, and search terms. The Category, Tag and subject filters are a little bit special. You can't type in the text box, in order to select what you would like to filter press the … button. Let's start with Categories. In the search bar you can filter the list of categories, just type in some text and then hit enter. If you don't find what you are looking for, you can clear the filter by pressing the X Button. Once you find what you are looking for, click the checkbox. Note that you can check off multiple categories. Once you are done, just press the accept button. Subject and tags work in the same way. If you want to filter by text, type into the search terms textbox. You can also specify what type of query by pressing the Or button to switch to an and query. Once you are set, you can hit enter, or press the go button. And as always, you can press the X button to clear the filter. Underneath the Filter Options, we have a list of the Modules and submodules. You can click a header with an arrow to the left to see the submodules. If you want to expand all the modules, press the expand all button at the bottom, you can also collapse all the modules by pressing the collapse all button.Finally, we get to the adding a header part of the tutorial. Double click the module you want to add and it gets inserted into the document. See you in the next video, where we talk about the Scan tool.",
"Hi and welcome back to the SRT video tutorial series. In this video we will be going into the Scan Document for Modules tool. On my document I have a few headers that I have inserted using the add headers tool, if you need to know how to use it refer to the previous video tutorial.  In order to use this tool, press this scan icon. The options that show up are different structure documents that you can choose from. Select the structure document you want to use, and the Select bookmarked Document modules window pops up. This shows all the module headers that were found, by default all of them are selected. If you would like to unselect everything, just double click the check all headers check box. You can specifically set which ones you want, or don't want, by check off the individual checkboxes infront of the module name. There is an apply styles checkbox at the top as well. What this does is that it applies the style that the deocument currently has to the module name. This would help you easily navigate much larger documents. Let's check off apply styles, and then press apply. Now we can see that the module names have been stylised based on word's current style. That's all there is to the Scan Document For Modules tool tutorial. I'll see you in the next one.",
];
  
function changeVideo(videonumber) {
	
  lastVideo = videonumber;
  document.getElementById("container").innerHTML = videoList[videonumber];
  document.getElementById("videoTitle").innerHTML = "<b>Transcript: </b>" + titleList[videonumber];
  document.getElementById("videoDescription").innerHTML = descriptionList[videonumber];
}
